site_name: Gittxt Docs
site_description: AI-ready text extractor for Git repositories
site_url: https://sandy-sp.github.io/gittxt
repo_url: https://github.com/sandy-sp/gittxt
repo_name: sandy-sp/gittxt
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: docs/overrides
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: grey
        accent: red
        toggle:
            icon: material/weather-sunny
            name: Switch to light mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: black
        accent: red
        toggle:
            icon: material/weather-night
            name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - navigation.instant
  logo: images/logo/gittxt.png

nav:
  - Home: index.md
  - About Gittxt: about.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - User Guide:
      - Scanning: user-guide/scanning.md
      - Output Formats: user-guide/output-formats.md
      - Reverse Engineering: user-guide/reverse-engineering.md
      - Configuration:
          - Overview: user-guide/configuration/index.md
          - CLI Flags: user-guide/configuration/cli-flags.md
          - Environment Variables: user-guide/configuration/environment-variables.md
          - .gittxtignore: user-guide/configuration/gittxtignore.md
          - Interactive Config: user-guide/configuration/interactive-config.md
          - Filter Manager: user-guide/configuration/filter-manager.md
      - Plugins:
          - Overview: user-guide/plugins/index.md
          - API Plugin: user-guide/plugins/api-plugin.md
          - Streamlit Plugin: user-guide/plugins/streamlit-plugin.md
  - CLI Reference:
      - Overview: cli-reference/index.md
      - Scan: cli-reference/scan.md
      - Config: cli-reference/config.md
      - Clean: cli-reference/clean.md
      - Reverse: cli-reference/re.md
      - Plugin: cli-reference/plugin.md
  - API Reference:
      - Overview: api-reference/index.md
      - Inspect Endpoint: api-reference/inspect-endpoint.md
  - Development:
      - Contributing: development/contributing.md
      - Code of Conduct: development/code-of-conduct.md
      - Test Suite: development/tests.md 
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  generator: false

