AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Gittxt Web API + Layer

Globals:
  Function:
    Timeout: 60
    MemorySize: 512

Resources:
  GittxtApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler.handler
      Runtime: python3.12
      CodeUri: ..
      Layers:
        - !Ref GittxtLayer
      Environment:
        Variables:
          GITTXT_OUTPUT_DIR: /tmp/gittxt-output
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /v1/{proxy+}
            Method: ANY

  GittxtLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gittxt-pypi-layer
      Description: Gittxt PyPI package
      ContentUri: ../layer       # we’ll create this next
      CompatibleRuntimes:
        - python3.12
      LicenseInfo: MIT
