services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: gittxt-api
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src             # Mount local Gittxt CLI code
      - ../api:/app                 # Mount FastAPI source
      - ./outputs:/app/outputs      # Persist scan outputs
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
